ftl/ftl/otp_plugins/otp_ftl/urls.py
#  Copyright (c) 2020 Exotic Matter SAS. All rights reserved.
#  Licensed under the Business Source License. See LICENSE at project root for more information.

from django.urls import path

from ftl.otp_plugins.otp_ftl import views, views_static, views_totp, views_fido2

urlpatterns = [
    path("", views.ListOTPDevices.as_view(), name="otp_list"),
    path("check/", views.OTPCheckView.as_view(), name="otp_check"),
    path("static/", views_static.StaticDeviceAdd.as_view(), name="otp_static_add"),
    path(
        "static/check/",
        views_static.StaticDeviceCheck.as_view(),
        name="otp_static_check",
    ),
    path(
        "static/<str:pk>/",
        views_static.StaticDeviceDetail.as_view(),
        name="otp_static_detail",
    ),
    path(
        "static/<str:pk>/update/",
        views_static.StaticDeviceUpdate.as_view(),
        name="otp_static_update",
    ),
    path(
        "static/<str:pk>/delete/",
        views_static.StaticDeviceDelete.as_view(),
        name="otp_static_delete",
    ),
    path("totp/", views_totp.TOTPDeviceAdd.as_view(), name="otp_totp_add"),
    path("totp/check/", views_totp.TOTPDeviceCheck.as_view(), name="otp_totp_check"),
    path(
        "totp/<str:pk>/", views_totp.TOTPDeviceDetail.as_view(), name="otp_totp_detail"
    ),
    path(
        "totp/<str:pk>/update/",
        views_totp.TOTPDeviceUpdate.as_view(),
        name="otp_totp_update",
    ),
    path(
        "totp/<str:pk>/delete/",
        views_totp.TOTPDeviceDelete.as_view(),
        name="otp_totp_delete",
    ),
    path(
        "totp/<str:pk>/qrcode/",
        views_totp.TOPTDeviceViewQRCode.as_view(),
        name="otp_totp_qrcode",
    ),
    path("fido2/", views_fido2.Fido2DeviceAdd.as_view(), name="otp_fido2_add"),
    path("fido2/check/", views_fido2.Fido2Check.as_view(), name="otp_fido2_check"),
    path(
        "fido2/success/",
        views_fido2.Fido2DeviceSuccess.as_view(),
        name="otp_fido2_success",
    ),
    path(
        "fido2/<str:pk>/update/",
        views_fido2.Fido2DeviceUpdate.as_view(),
        name="otp_fido2_update",
    ),
    path(
        "fido2/<str:pk>/delete/",
        views_fido2.Fido2DeviceDelete.as_view(),
        name="otp_fido2_delete",
    ),
    path(
        "fido2/api/register_begin",
        views_fido2.fido2_api_register_begin,
        name="otp_fido2_api_register_begin",
    ),
    path(
        "fido2/api/register_finish",
        views_fido2.fido2_api_register_finish,
        name="otp_fido2_api_register_finish",
    ),
    path(
        "fido2/api/login_begin",
        views_fido2.fido2_api_login_begin,
        name="otp_fido2_api_login_begin",
    ),
]

ftl/ftl/urls.py
#  Copyright (c) 2020 Exotic Matter SAS. All rights reserved.
#  Licensed under the Business Source License. See LICENSE at project root for more information.

from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include, re_path, reverse_lazy
from django.views.generic import RedirectView
from django_registration.backends.activation.views import ActivationView

from ftl import views
from ftl.forms import FTLAuthenticationForm
from ftl.ftl_setup_middleware import SetupState
from ftl.views import PasswordResetAsked, PasswordResetDone

urlpatterns = [
    path("admin/", admin.site.urls),
    # Need to be at the top, otherwise admin url resolve conflict with other urls
    path("", RedirectView.as_view(url=reverse_lazy("home")), name="root"),
    path("setup/", include("setup.urls")),
    path("app/", include("core.urls")),
    path("signup/", views.CreateOrgAndFTLUser.as_view(), name="signup_org_user"),
    path("signup/success/", views.signup_success, name="signup_success"),
    # Disabled until multi users feature is ready
    # path('signup/<slug:org_slug>/', views.CreateFTLUserFormView.as_view(), name='signup_user'),
    path(
        "login/",
        auth_views.LoginView.as_view(
            authentication_form=FTLAuthenticationForm, redirect_authenticated_user=True
        ),
        kwargs={"ftl_setup_state": SetupState.admin_created},
        name="login",
    ),
    path("logout/", auth_views.logout_then_login, name="logout"),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/", PasswordResetAsked.as_view(), name="password_reset_done"
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("reset/done/", PasswordResetDone.as_view(), name="password_reset_complete"),
    # Account management
    path("accounts/", include("account.urls")),
    # Account activation
    path(
        "accounts/activate/complete/",
        views.AccountActivationSuccess.as_view(),
        name="django_registration_activation_complete",
    ),
    # The activation key can make use of any character from the URL-safe base64 alphabet, plus the colon as a separator.
    url(
        r"^accounts/activate/(?P<activation_key>[-:\w]+)/$",
        ActivationView.as_view(),
        name="django_registration_activate",
    ),
    # OTP
    path("accounts/2fa/", include("ftl.otp_plugins.otp_ftl.urls")),
    # OAuth2 Provider
    path("oauth2/", include("ftl.urls_oauth2")),
    # Captcha
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG and settings.DEV_MODE:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

if settings.DEV_MODE:
    from ftl import view_local_proxy

    urlpatterns += [
        re_path(r"^local/(?P<url>.*)$", view_local_proxy.LocalProxy.as_view())
    ]

ftl/ftl/otp_plugins/otp_ftl/forms.py
#  Copyright (c) 2020 Exotic Matter SAS. All rights reserved.
#  Licensed under the Business Source License. See LICENSE at project root for more information.

from django import forms
from django.forms import Form
from django.utils.translation import gettext_lazy as _
from django_otp import devices_for_user
from django_otp.forms import OTPTokenForm
from django_otp.plugins.otp_static.models import StaticDevice, StaticToken
from django_otp.plugins.otp_totp.models import TOTPDevice

from ftl.otp_plugins.otp_ftl.models import Fido2Device


# Forms for checking 2FA
class StaticDeviceCheckForm(OTPTokenForm):
    otp_device = forms.ChoiceField(
        label=_("Set of emergency codes"),
        help_text=_("Select set of codes to use"),
        choices=[],
    )
    otp_token = forms.CharField(
        required=True,
        label=_("Code"),
        strip=True,
        help_text=_(
            "One emergency code from your set (alphanumeric code, it will be consumed)"
        ),
    )
    otp_challenge = None

    def __init__(self, user, request=None, *args, **kwargs):
        super(OTPTokenForm, self).__init__(*args, **kwargs)

        self.user = user

        self.fields["otp_device"].choices = self._get_valid_choices(user)

    def _get_valid_choices(self, user):
        # Only show sets that still contains codes
        choices = [
            d
            for d in devices_for_user(user)
            if StaticDevice.model_label() in d.persistent_id and d.token_set.exists()
        ]
        choices_with_token = list((d.persistent_id, d.name) for d in choices)
        return choices_with_token

    def _update_form(self, user):
        super()._update_form(user)

        if "otp_device" in self.fields:
            self.fields["otp_device"].widget.choices = self._get_valid_choices(user)

    def _verify_token(self, user, token, device=None):
        return super()._verify_token(user, token.upper(), device)


class TOTPDeviceCheckForm(OTPTokenForm):
    otp_device = forms.ChoiceField(
        label=_("Authenticator app"),
        help_text=_("Select the authenticator app you wish to use"),
        choices=[],
    )
    otp_token = forms.CharField(
        required=True,
        label=_("Code"),
        strip=True,
        help_text=_("Two factor code shown in your app authenticator (only numbers)"),
    )
    otp_challenge = None

    def __init__(self, user, request=None, *args, **kwargs):
        super(OTPTokenForm, self).__init__(*args, **kwargs)

        self.user = user
        # filter user OTP devices to keep only TOTP ones
        self.fields["otp_device"].choices = [
            d for d in self.device_choices(user) if TOTPDevice.model_label() in d[0]
        ]

    def _update_form(self, user):
        super()._update_form(user)

        if "otp_device" in self.fields:
            # filter user OTP devices to keep only TOTP ones
            self.fields["otp_device"].widget.choices = [
                d for d in self.device_choices(user) if TOTPDevice.model_label() in d[0]
            ]


class Fido2DeviceCheckForm(OTPTokenForm):
    otp_device = None
    otp_token = forms.CharField(required=True, widget=forms.HiddenInput())
    otp_challenge = None

    def __init__(self, user, request=None, *args, **kwargs):
        super(OTPTokenForm, self).__init__(*args, **kwargs)
        self.user = user
        self.request = request

    def clean(self):
        # filter user OTP devices to keep only FIDO2 ones
        fido2_devices = [
            d
            for d in self.device_choices(self.user)
            if Fido2Device.model_label() in d[0]
        ]
        # We choose a default Fido 2 device to satisfy the requirement of the form but the field itself is not used
        # by the final submit request as the check uses its own API views_fido2.fido2_api_login_begin (which return
        # all the user keys).
        self.cleaned_data["otp_device"] = fido2_devices[0][0]
        return super().clean()

    def _verify_token(self, user, token, device=None):
        state = self.request.session.pop("fido2_state")
        domain = self.request.session.pop("fido2_domain")
        return super()._verify_token(
            user, {"token": token, "state": state, "domain": domain}, device
        )


# Forms for registering a new device
class StaticDeviceForm(Form):
    name = forms.CharField(
        label="Name",
        strip=True,
        initial=_("Emergency codes"),
        help_text=_("Indicate a name to recognize your two factor device"),
    )

    def save(self, user):
        static_device = StaticDevice(name=self.cleaned_data["name"], user=user)
        static_device.save()

        for i in range(10):
            code = StaticToken(token=StaticToken.random_token().upper())
            code.device = static_device
            code.save()

        return static_device


class TOTPDeviceForm(Form):
    name = forms.CharField(
        label="Name",
        strip=True,
        initial=_("Authenticator app"),
        help_text=_("Indicate a name to recognize your two factor device"),
    )

    def save(self, user):
        totp_device = TOTPDevice(name=self.cleaned_data["name"], user=user)
        totp_device.confirmed = False
        totp_device.save()

        return totp_device


# Form to confirm registration of a new device
class TOTPDeviceConfirmForm(OTPTokenForm):
    otp_device = None
    otp_token = forms.CharField(
        required=True,
        label=_("Code"),
        strip=True,
        help_text=_("Two factor code shown in your app authenticator (only numbers)"),
    )
    otp_challenge = None

    def __init__(self, user, device, request=None, *args, **kwargs):
        super(OTPTokenForm, self).__init__(*args, **kwargs)
        self.user = user
        self.device = device

    def clean(self):
        self.cleaned_data["otp_device"] = self.device.persistent_id
        return super().clean()

ftl/ftl/otp_plugins/otp_ftl/views.py
#  Copyright (c) 2021 Exotic Matter SAS. All rights reserved.
#  Licensed under the Business Source License. See LICENSE in the project root for more information.

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views import View
from django.views.generic import DeleteView
from django_otp import devices_for_user
from django_otp.decorators import otp_required
from django_otp.plugins.otp_static.models import StaticDevice, StaticToken
from django_otp.plugins.otp_totp.models import TOTPDevice

from core.ftl_account_processors_mixin import FTLAccountProcessorContextMixin
from ftl.otp_plugins.otp_ftl.models import Fido2Device
from ftl.views_auth import LoginViewFTL


@method_decorator(login_required, name="dispatch")
@method_decorator(otp_required(if_configured=True), name="dispatch")
class ListOTPDevices(FTLAccountProcessorContextMixin, View):
    def get(self, request, *args, **kwargs):
        user = request.user
        # Static token
        static_devices = StaticDevice.objects.filter(user=user)

        # TOTP
        totp_devices = TOTPDevice.objects.filter(user=user)

        # FIDO2
        fido2_devices = Fido2Device.objects.filter(user=user)

        context_data = self.get_context_data()
        context_data.update(
            {
                "static_devices": static_devices,
                "totp_devices": totp_devices,
                "fido2_devices": fido2_devices,
            }
        )

        return render(request, "otp_ftl/device_list.html", context_data)


@method_decorator(login_required, name="dispatch")
class OTPCheckView(View):
    def get(self, request, *args, **kwargs):
        # Reduce session expiration to 10 minutes during 2FA check (in case user afk).
        request.session.set_expiry(600)

        devices = list(
            (d.persistent_id, d.name) for d in devices_for_user(request.user)
        )
        _next = request.GET.get("next", None)
        if _next:
            request.session["next"] = _next

        # Redirect to available device check page, from most secure to less secure one
        if [d for d in devices if Fido2Device.model_label() in d[0]]:
            return redirect("otp_fido2_check", *args, **kwargs)

        if [d for d in devices if TOTPDevice.model_label() in d[0]]:
            return redirect("otp_totp_check", *args, **kwargs)

        if [d for d in devices if StaticDevice.model_label() in d[0]]:
            return redirect("otp_static_check", *args, **kwargs)


class FTLBaseCheckView(LoginViewFTL):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["have_fido2"] = Fido2Device.objects.filter(
            user=self.request.user, confirmed=True
        ).exists()
        context["have_totp"] = TOTPDevice.objects.filter(
            user=self.request.user, confirmed=True
        ).exists()
        context["have_static"] = StaticToken.objects.filter(
            device__user=self.request.user
        ).exists()
        return context

    def get_success_url(self):
        url = self.request.session.get("next", None)
        if url:
            del self.request.session["next"]
            url_is_safe = is_safe_url(
                url=url,
                allowed_hosts=self.get_success_url_allowed_hosts(),
                require_https=self.request.is_secure(),
            )
            return url if url_is_safe else self.success_url

        return self.success_url

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        # Restore session expiration to default value
        self.request.session.set_expiry(None)
        return super().form_valid(form)


class FTLBaseDeleteView(DeleteView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        have_fido2 = Fido2Device.objects.filter(user=self.request.user, confirmed=True)
        if self.model is Fido2Device:
            have_fido2 = have_fido2.exclude(pk=self.object.pk)
        have_fido2 = have_fido2.exists()

        have_totp = TOTPDevice.objects.filter(user=self.request.user, confirmed=True)
        if self.model is TOTPDevice:
            have_totp = have_totp.exclude(pk=self.object.pk)
        have_totp.exists()

        context["last_otp"] = not have_fido2 and not have_totp
        return context

    def delete(self, request, *args, **kwargs):
        delete = super().delete(request, *args, **kwargs)

        if self.get_context_data()["last_otp"]:
            Fido2Device.objects.filter(user=self.request.user).delete()
            TOTPDevice.objects.filter(user=self.request.user).delete()
            StaticDevice.objects.filter(user=self.request.user).delete()

        return delete

ftl/ftl/otp_plugins/otp_ftl/templates/otp_ftl/device_update.html
{% extends 'account/account_base.html' %}
{% load i18n %}

{% block account %}
    <h3 class="text-primary">{% trans 'Rename device' %}</h3>

    <form method="post">{% csrf_token %}
        <div class="form-group">
            <label for="id_name">{% trans 'Device name' %}</label>
            <input type="text" name="name" value="{{ form.name.value }}" placeholder="{% trans 'Device name' %}"
                   required="required" id="id_name" class="form-control">
            <small class="form-text text-muted">{% trans 'Name to recognize your two factor device' %}</small>
        </div>

        <a class="btn btn-secondary float-left" href="{% url 'otp_list' %}">{% trans 'Cancel' %}</a>
        <input type="submit" class="btn btn-primary float-right" value="{% trans 'Rename' %}">
    </form>
{% endblock %}

{% block js_script_head %}
    <script nonce="{{ request.csp_nonce }}" type="application/javascript">
        document.addEventListener("DOMContentLoaded", function() {
            const elem = document.getElementById("id_name");
            elem.addEventListener("focus", elem.select);
        });
    </script>
{% endblock %}

ftl/ftl/otp_plugins/otp_ftl/templates/otp_ftl/fido2device_form.html
{% extends 'account/account_base.html' %}
{% load static %}
{% load i18n %}

{% block js_script_head %}
    <script type="application/javascript" src="{% static 'cbor.js' %}"></script>
{% endblock %}

{% block account %}
    <h3 class="text-primary">{% trans "Add a security key" %}</h3>

    <p class="font-italic">
        {% blocktrans %}
            A security key dongle is a small device that you can buy to help prove it’s you signing in: you simply have
            to connect the key to your phone, tablet, or computer.
        {% endblocktrans %}
    </p>
    <p class="highlight text-justify">
        {% blocktrans %}
            Such keys are the ones that are compatible with the U2F or FIDO2 protocol
            (Yubikey, Google Titan Security Key, etc.).<br/>
            Only recent browsers are compatible with these keys such as Google Chrome, Mozilla Firefox,
            Microsoft Edge.
        {% endblocktrans %}
    </p>

    <form id="fido-form">
        <div class="form-group">
            <label for="id_name">{% trans 'Security key name' %}</label>
            <input type="text" name="name" placeholder="{% trans 'Security key with house key' %}"
                   required="required" id="id_name" class="form-control" autofocus="autofocus">
            <small class="form-text text-muted">{% trans 'A name to identify your security key' %}</small>
        </div>
        {% if request.GET.error %}
            <div class="alert alert-danger">
                {% if request.GET.error == 'abort' %}
                    {% trans 'Browser prompt asking for the key was cancel' %}
                {% elif request.GET.error == 'not-allowed' %}
                    {% trans 'Browser prompt asking for the key was ignore or refused' %}
                {% elif request.GET.error == 'registration-begin-api' or request.GET.error == 'registration-finish-api' %}
                    {% blocktrans %}
                        Key registration failed, make sure your key type is supported. <br/>
                        Registration could also fail if page url isn't in https. <br/>
                    {% endblocktrans %}
                {% elif request.GET.error == 'network' %}
                    {% trans 'A network error occurred during key registration, try again' %}
                {% elif request.GET.error == 'cbor-decode' or request.GET.error == 'cbor-encode' %}
                    {% trans 'An internal error occured during key registration, you may have found a bug' %}
                {% elif request.GET.error == 'duplicate-key' %}
                    {% trans 'This key is already registred' %}
                {% elif request.GET.error == 'unknown-generic' or request.GET.error == 'unknown-generic' %}
                    {% trans 'An unknown error occured during key registration, you may have found a bug' %}
                {% elif request.GET.error == 'unexpected' %}
                    {% trans 'An unexpected error occured during key registration, you may have found a bug' %}
                {% endif %}
                <i>({% trans 'error code: ' %}{{ request.GET.error }})</i>
            </div>
        {% endif %}
        <a class="btn btn-secondary float-left" href="{% url 'otp_list' %}">{% trans 'Cancel' %}</a>
        <input id="fido2-next" class="btn btn-primary float-right" type="submit" value="{% trans 'Next' %}">
    </form>


{% endblock %}

{% block before_footer %}
    <script nonce="{{ request.csp_nonce }}" type="application/javascript">
        "use strict";

        const submit = document.getElementById("fido-form");

        submit.addEventListener("submit", function(event) {
            event.preventDefault();

            {# CBOR lib come from cbor.js static file, included by script tag at the top of this file #}

            fetch('{% url 'otp_fido2_api_register_begin' %}', {
                method: "POST"
            })
                    .then(function(response) {
                        if (response.ok) {
                            return response.arrayBuffer();
                        } else {
                            throw new Error("RegistrationBeginApiError");
                        }
                    })
                    .then(function(value) {
                        try {
                            return CBOR.decode(value);
                        } catch (e) {
                            throw new Error("CBORDecodeError");
                        }
                    })
                    .then(function(options) {
                                return navigator.credentials.create(options);
                            }
                    )
                    .then(function(attestation) {
                        const deviceName = document.getElementById("id_name").value;
                        try {
                            return CBOR.encode({
                                "attestationObject": new Uint8Array(attestation.response.attestationObject),
                                "clientDataJSON": new Uint8Array(attestation.response.clientDataJSON),
                                "name": deviceName
                            });
                        } catch (e) {
                            throw new Error("CBOREncodeError");
                        }
                    })
                    .then(function(body) {
                        return fetch('{% url 'otp_fido2_api_register_finish' %}', {
                            method: "POST",
                            headers: { "Content-Type": "application/cbor" },
                            body: body
                        });
                    })
                    .then(function(response) {
                        if (response.ok) {
                            window.location = '{% url 'otp_fido2_success'  %}';
                        } else {
                            // could occur when page isn't loaded in https
                            throw new Error("RegistrationFinishApiError");
                        }
                    })
                    .catch(function(error) {
                        let errorCode;

                        if ("name" in error) {
                            if (error.name === "AbortError") {
                                errorCode = "abort";
                            } else if (error.name === "InvalidStateError" && "message" in error &&
                                    // Chrome 80 error
                                    (error.message.includes("already registered") ||
                                            // Firefox 73 error
                                            error.message.includes("use an object that is not, or is no longer, usable"))) {
                                errorCode = "duplicate-key";
                            } else if (error.name === "NotAllowedError") {
                                errorCode = "not-allowed";
                            } else if (error.name === "TypeError" && "message" in error &&
                                    error.message.includes("NetworkError")) {
                                errorCode = "network";
                            } else if (error.name === "Error") {
                                if ("message" in error) {
                                    if (error.message === "RegistrationBeginApiError") {
                                        errorCode = "registration-begin-api";
                                    } else if (error.message === "RegistrationFinishApiError") {
                                        errorCode = "registration-finish-api";
                                    } else if (error.message === "CBORDecodeError") {
                                        errorCode = "cbor-decode";
                                    } else if (error.message === "CBOREncodeError") {
                                        errorCode = "cbor-encode";
                                    }
                                } else {
                                    errorCode = "unknown-generic";
                                }
                            } else {
                                errorCode = "unexpected";
                            }
                        } else {
                            errorCode = "unknown-nameless";
                        }
                        window.location = `{% url 'otp_fido2_add' %}?error=${errorCode}`;
                    });
        });
    </script>
{% endblock %}

ftl/ftl/otp_plugins/otp_ftl/templates/otp_ftl/staticdevice_check.html
{% extends "ftl/main_with_aside.html" %}
{% load i18n %}
{% load static %}
{% load add_attr %}
{% load webpack_loader %}

{% block title %}{% trans "Two-step Verification" %}{% endblock %}

{% block head %}{% render_bundle 'common_logged_out' 'css' %}{% endblock %}

{% block main_content %}
    <h1 class="text-primary">
        {% trans "Two-step Verification" %}
    </h1>

    <p>{% trans "This extra step shows that it’s really you trying to sign in" %}</p>

    {% if form.otp_device.field.choices %}
        <form method="post" id="user-form">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_otp_device">{{ form.otp_device.label }}</label>
                {{ form.otp_device|add_attr:'{"class":"form-control"}' }}
                <small class="form-text text-muted">{{ form.otp_device.help_text }}</small>
            </div>

            <div class="form-group">
                <label for="id_otp_token">{{ form.otp_token.label }}</label>
                <input type="text" name="otp_token" value="" required="required" id="id_otp_token"
                       placeholder="XXXXXXXX" pattern="[a-zA-Z0-9]*" autofocus="autofocus"
                       class="form-control{% if form.errors %} is-invalid{% endif %}" autocomplete="no">
                <small class="form-text text-muted">{{ form.otp_token.help_text }}</small>
            </div>

            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% trans 'Incorrect code' %}
                </div>
            {% endif %}

            <input class="btn btn-lg btn-primary btn-block" type="submit" value="{% trans "Verify" %}">
        </form>
    {% else %}
        <p>{% trans "Error: you can't use emergency code on this account." %}</p>
    {% endif %}

    <div class="text-center">
        <a href="{% url 'logout' %}" class="btn btn-sm btn-link">{% trans 'Cancel' %}</a>
    </div>

    {% if have_fido2 or have_totp %}
        <p>{% trans "Try another way" %}</p>
        <ul id="alternatives-list">
            {% if have_fido2 %}
                <li><a href="{% url "otp_fido2_check" %}">{% trans "Use your security key" %}</a></li>
            {% endif %}
            {% if have_totp %}
                <li><a href="{% url "otp_totp_check" %}">{% trans "Use a code from your authentication app" %}</a></li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

{% block aside_illustration %}
    <img src="{% static "two_factor_authentication.svg" %}" alt="Signup steps illustration">
{% endblock %}

ftl/ftl/otp_plugins/otp_ftl/templates/otp_ftl/totpdevice_check.html
{% extends "ftl/main_with_aside.html" %}
{% load i18n %}
{% load static %}
{% load add_attr %}
{% load webpack_loader %}

{% block title %}{% trans "Two-step Verification" %}{% endblock %}

{% block head %}{% render_bundle 'common_logged_out' 'css' %}{% endblock %}

{% block main_content %}
    <h1 class="text-primary">
        {% trans "Two-step Verification" %}
    </h1>

    <p>{% trans "This extra step shows that it’s really you trying to sign in" %}</p>

    {% if form.otp_device.field.choices %}
        <form method="post" id="user-form">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_otp_device">{{ form.otp_device.label }}</label>
                {{ form.otp_device|add_attr:'{"class":"form-control"}' }}
                <small class="form-text text-muted">{{ form.otp_device.help_text }}</small>
            </div>

            <div class="form-group">
                <label for="id_otp_token">{{ form.otp_token.label }}</label>
                <input type="text" name="otp_token" value="" placeholder="XXX XXX" required="required" id="id_otp_token"
                       class="form-control{% if form.errors %} is-invalid{% endif %}" inputmode="numeric"
                       pattern="[0-9]*" autocomplete="one-time-code" autofocus="autofocus">
                <small class="form-text text-muted">{{ form.otp_token.help_text }}</small>
            </div>

            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% trans 'Incorrect code' %}
                </div>
            {% endif %}

            <input class="btn btn-lg btn-primary btn-block" type="submit" value="{% trans "Verify" %}">
        </form>
    {% else %}
        <p>{% trans "Error: you can't use an authenticator app on this account." %}</p>
    {% endif %}

    <div class="text-center">
        <a href="{% url 'logout' %}" class="btn btn-sm btn-link">{% trans 'Cancel' %}</a>
    </div>

    {% if have_fido2 or have_static %}
        <p>{% trans "Try another way" %}</p>
        <ul id="alternatives-list">
            {% if have_fido2 %}
                <li><a href="{% url "otp_fido2_check" %}">{% trans "Use your security key" %}</a></li>
            {% endif %}
            {% if have_static %}
                <li><a href="{% url "otp_static_check" %}">{% trans "Use a one time emergency code" %}</a></li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

{% block aside_illustration %}
    <img src="{% static "two_factor_authentication.svg" %}" alt="Signup steps illustration">
{% endblock %}